[features]
seeds = false
skip-lint = false

[programs.localnet]
verdant_escrow = "Verdant111111111111111111111111111111111111"

[programs.devnet]
verdant_escrow = "Verdant111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
